[package]
name = "wf_lab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphics = { path = "../graphics_wgpu" }
lin-alg2 = { path = "../lin_alg" }
egui = "^0.19"

# Tempish: These are for adapting the RBF lib
rulinalg = "^0.4"
error-chain = "0.10"

# todo: Experimenting with auot-diff
# autodiff = "^0.6.0"