[package]
name = "wf_lab"
version = "0.1.0"
edition = "2021"


[dependencies]
graphics = { path = "../graphics_wgpu" }
lin-alg2 = { path = "../lin_alg" }
egui = "^0.19"

# We use Scilib for computing H basis fns, eg with Laguerre and Legendre polynomials.
scilib = "^1.0.0"

# Attempting to solve linear systems of equations for basis finding
ndarray = "^0.15.6"
ndarray-linalg = { version = "^0.16.0", features = ["intel-mkl-static"] }


nalgebra = "^0.32.3"

# todo: Eventually ditch this tool for permutations:
itertools = "^0.11.0"

# todo: Should these be build-dependencies or normal? Which of the 2 do you want?
# What about `std::ffi`?

libc = "^0.2.149"

# rulinalg = "^0.4" # Tempish: For adapting the RBF lib

[build-dependencies]
# For CUDA FFI
cc = { version = "^1.0.83", features = ["parallel"] }

